version: "3"
services:
  server:
    build:
      dockerfile: packages/server/Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    command: yarn dev
    volumes:
      - ./packages/server:/server
        # node-modules should not be synced
      - /server/node_modules
    environment:
      NODE_ENV: dev
      PORT: $SERVER_PORT
      PGHOST: database
      PGDATABASE: $PGDATABASE
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
    depends_on:
      - database
  dashboard:
    build:
      dockerfile: packages/dashboard/Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - $DASHBOARD_PORT:$DASHBOARD_PORT
    command: yarn dev
    volumes:
      - ./packages/dashboard:/dashboard
        # node-modules should not be synced
      - /dashboard/node_modules
    environment:
      NODE_ENV: dev
      PORT: $DASHBOARD_PORT
  database:
    image: postgres:13
    command: postgres
    ports:
      - $PGPORT:$PGPORT
    environment:
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
