import klart from "klart";
import { User } from "./models";

function persistUser() {
  return klart.first<User>(
    `
    -- only value is .id, and it is autogenerated
    INSERT INTO users DEFAULT VALUES
    RETURNING *;
    `
  );
}

export const users = {
  persistUser,
};
